### ISSUE TITLE
[Feature request] List compatible applications

### ISSUE THREAD

**Issue by dlabouesse** [QwantResearch/masq-app#124]
It would be great to have the list of the applications that are compatible with Masq in the `Applications` view. (At least Qwant's applications.)

This would help the users to see the value of Masq by indicating where Masq can be used, rather than displaying a default blank screen and thus force them to figure out by themselves where Masq can be used.

**Comment by G-Ray** [comment]
Thank you @dlabouesse for you suggestion.

We added a list of recommended apps in https://github.com/QwantResearch/masq-app/pull/131. You will be able to see this section in the next release if you don't have `Qwant Maps` already added to your apps.

Please note we only have integration done with Qwant Maps for now.

**Comment by G-Ray** [comment]
This is now visible in production at masq.qwant.com, thank you @dlabouesse
