### ISSUE TITLE
Invalid password with some special characters

### ISSUE THREAD

**Issue by Booteille** [QwantResearch/masq-app#135]
I generated a password with KeePassXC but it has not been accepted.
I think the error message is not representative of the exact issue here since I respect all rules but the error says I don't.

![Screenshot_2019-07-08 Masq by Qwant](https://user-images.githubusercontent.com/2203721/60822674-3bb6f580-a1a6-11e9-95f7-9f0fd6d57659.png)

**Comment by G-Ray** [comment]
Thank you for your bug report @Booteille .

We were authorizing a whitelist of special characters, but failed to display an error to the user if a character was not in the whitelist.

We fixed this issue in https://github.com/QwantResearch/masq-app/pull/129.
From now you will be able to use any special characters. This will be visible as soon as we ship a new release to production. This should be a matter of days :rocket:

**Comment by Booteille** [comment]
Okay, thanks! I'll try it again in some days!

Have a great day.

**Comment by G-Ray** [comment]
@Booteille The fix is deployed on https://masq.qwant.com, I'm closing the issue, thanks again
