### ISSUE TITLE
[Translation] Missing English translation in "My devices" page

### ISSUE THREAD

**Issue by deiu** [QwantResearch/masq-app#140]
Hi,

The English translation is not applied (or is missing) to entries in "My devices" page.

<img width="485" alt="Screen Shot 2019-07-31 at 12 07 21" src="https://user-images.githubusercontent.com/346820/62199233-cf39ab80-b38b-11e9-858c-2b987f325fc4.png">

**Comment by Charlotte-Ziegler** [comment]
Thanks, for information we just correct that translation.
